services:
  mongodb:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  todo-app:
    build: .
    ports:
      - "5080:8080"
    depends_on:
      - mongodb
    environment:
      MongoDb__ConnectionString: "mongodb://mongodb:27017"

volumes:
  mongo-data:
